
def dict_crypto_list_name():
    my_dict={'BTC': ['Bitcoin', 'bitcoin'],
             'WBTC': ['Wrapped Bitcoin', 'wrapped-bitcoin'],
             'USDT': ['TetherUS', 'tetherus'],
             'YFI': ['yearn.finance', 'yearn-finance'],
             'PAXG': ['PAX Gold', 'pax-gold'],
             'ETH': ['Ethereum', 'ethereum'],
             'BETH': ['BETH', 'beth'],
             'YFII': ['DFI.Money', 'dfi-money'],
             'MKR': ['Maker', 'maker'],
             'BIFI': ['Beefy.Finance', 'beefy-finance'],
             'BNB': ['BNB', 'bnb'],
             'AUTO': ['Auto', 'auto'],
             'BNX': ['BinaryX', 'binaryx'],
             'XMR': ['Monero', 'monero'],
             'QNT': ['Quant', 'quant'],
             'BCH': ['Bitcoin Cash', 'bitcoin-cash'],
             'KP3R': ['Keep3rV1', 'keep3rv1'],
             'AAVE': ['Aave', 'aave'],
             'COMP': ['Compound', 'compound'],
             'ILV': ['Illuvium', 'illuvium'],
             'QUICK': ['QuickSwap', 'quickswap'],
             'ZEC': ['Zcash', 'zcash'],
             'LTC': ['Litecoin', 'litecoin'],
             'EGLD': ['Elrond eGold', 'elrond-egold'],
             'KSM': ['Kusama', 'kusama'],
             'DASH': ['Dash', 'dash'],
             'FARM': ['Harvest Finance', 'harvest-finance'],
             'BNBUP': ['BNBUP', 'bnbup'],
             'SOL': ['Solana', 'solana'],
             'ETC': ['Ethereum Classic', 'ethereum-classic'],
             'DCR': ['Decred', 'decred'],
             'FTT': ['FTX Token', 'ftx-token'],
             'ALCX': ['Alchemix', 'alchemix'],
             'BTG': ['Bitcoin Gold', 'bitcoin-gold'],
             'MLN': ['Enzyme', 'enzyme'],
             'SANTOS': ['Santos FC Fan Token', 'santos-fc-fan-token'],
             'AVAX': ['Avalanche', 'avalanche'],
             'TRB': ['Tellor Tributes', 'tellor-tributes'],
             'ENS': ['Ethereum Name Service', 'ethereum-name-service'],
             'WNXM': ['Wrapped NXM', 'wrapped-nxm'],
             'DOTDOWN': ['DOTDOWN', 'dotdown'],
             'NMR': ['Numeraire', 'numeraire'],
             'CREAM': ['Cream Finance', 'cream-finance'],
             'ZEN': ['Horizen', 'horizen'],
             'ATOM': ['Cosmos', 'cosmos'],
             'AXS': ['Axie Infinity', 'axie-infinity'],
             'SSV': ['SSV Token', 'ssv-token'],
             'MOVR': ['Moonriver', 'moonriver'],
             'AR': ['Arweave', 'arweave'],
             'LPT': ['Livepeer', 'livepeer'],
             'WING': ['WING', 'wing'],
             'NEO': ['NEO', 'neo'],
             'BTCST': ['Bitcoin Standard Hashrate Token',
              'bitcoin-standard-hashrate-token'],
             'PSG': ['Paris Saint-Germain Fan Token', 'paris-saint-germain-fan-token'],
             'LINK': ['ChainLink', 'chainlink'],
             'REP': ['Augur v2', 'augur-v2'],
             'LAZIO': ['Lazio Fan Token', 'lazio-fan-token'],
             'CITY': ['Manchester City Fan Token', 'manchester-city-fan-token'],
             'UNI': ['Uniswap', 'uniswap'],
             'AUCTION': ['Auction', 'auction'],
             'TORN': ['Tornado Cash', 'tornado-cash'],
             'DOT': ['Polkadot', 'polkadot'],
             'UNFI': ['Unifi Protocol DAO', 'unifi-protocol-dao'],
             'ICP': ['Internet Computer', 'internet-computer'],
             'BAR': ['FC Barcelona Fan Token BAR', 'fc-barcelona-fan-token-bar'],
             'PORTO': ['FC Porto Fan Token', 'fc-porto-fan-token'],
             'FIL': ['Filecoin', 'filecoin'],
             'PROM': ['Prometeus', 'prometeus'],
             'OG': ['OG Fan Token', 'og-fan-token'],
             'APE': ['ApeCoin', 'apecoin'],
             'BAL': ['Balancer', 'balancer'],
             'BOND': ['BarnBridge', 'barnbridge'],
             'HNT': ['Helium', 'helium'],
             'JUV': ['Juventus Fan Token', 'juventus-fan-token'],
             'CVX': ['Convex Finance', 'convex-finance'],
             'XVS': ['Venus', 'venus'],
             'FORTH': ['Ampleforth Governance Token', 'ampleforth-governance-token'],
             'ATM': ['Atlético de Madrid Fan Token', 'atlético-de-madrid-fan-token'],
             'CAKE': ['PancakeSwap', 'pancakeswap'],
             'FXS': ['Frax Share', 'frax-share'],
             'MULTI': ['Multichain', 'multichain'],
             'ERN': ['Ethernity Chain', 'ethernity-chain'],
             'ALPINE': ['Alpine F1 Team Fan Token', 'alpine-f1-team-fan-token'],
             'ACM': ['AC Milan Fan Token', 'ac-milan-fan-token'],
             'BTCUP': ['BTCUP', 'btcup'],
             'ASR': ['AS Roma Fan Token', 'as-roma-fan-token'],
             'WAVES': ['Waves', 'waves'],
             'BADGER': ['Badger DAO', 'badger-dao'],
             'PYR': ['Vulcan Forged PYR', 'vulcan-forged-pyr'],
             'NEAR': ['NEAR Protocol', 'near-protocol'],
             'ETHUP': ['ETHUP', 'ethup'],
             'DEXE': ['DeXe', 'dexe'],
             'FIRO': ['Firo', 'firo'],
             'QTUM': ['Qtum', 'qtum'],
             'NEBL': ['Neblio', 'neblio'],
             'GAL': ['Galxe', 'galxe'],
             'LUNA': ['Terra', 'terra'],
             'SNX': ['Synthetix Network Token', 'synthetix-network-token'],
             'UMA': ['UMA', 'uma'],
             'GAS': ['NeoGas', 'neogas'],
             'RAD': ['RAD', 'rad'],
             'GTC': ['Gitcoin', 'gitcoin'],
             'DEGO': ['Dego Finance', 'dego-finance'],
             'OMG': ['OMG Network', 'omg-network'],
             'INJ': ['Injective Protocol', 'injective-protocol'],
             'ALICE': ['My Neighbor Alice', 'my-neighbor-alice'],
             'FLOW': ['Flow', 'flow'],
             'ANT': ['Aragon', 'aragon'],
             'API3': ['API3', 'api3'],
             'LDO': ['Lido DAO', 'lido-dao'],
             'RUNE': ['THORChain', 'thorchain'],
             'KAVA': ['Kava', 'kava'],
             'HIGH': ['Highstreet', 'highstreet'],
             'XTZ': ['Tezos', 'tezos'],
             'KDA': ['Kadena', 'kadena'],
             'DYDX': ['dYdX', 'dydx'],
             'BAND': ['BAND', 'band'],
             'TRXDOWN': ['TRXDOWN', 'trxdown'],
             'RLC': ['iExecRLC', 'iexecrlc'],
             'EOS': ['EOS', 'eos'],
             'GHST': ['Aavegotchi', 'aavegotchi'],
             'KNC': ['KyberNetwork', 'kybernetwork'],
             'MASK': ['Mask Network', 'mask-network'],
             'ETHDOWN': ['ETHDOWN', 'ethdown'],
             'GBP': ['Pound Sterling', 'pound-sterling'],
             'ORN': ['Orion Protocol', 'orion-protocol'],
             'SUSHI': ['Sushi', 'sushi'],
             'THETA': ['Theta Token', 'theta-token'],
             'MTL': ['Metal', 'metal'],
             'BUSD': ['BUSD', 'busd'],
             'EUR': ['Euro', 'euro'],
             'BURGER': ['BurgerCities', 'burgercities'],
             'LSK': ['Lisk', 'lisk'],
             'SCRT': ['Secret', 'secret'],
             'OP': ['Optimism', 'optimism'],
             'CRV': ['Curve', 'curve'],
             'NEXO': ['Nexo', 'nexo'],
             'TWT': ['Trust Wallet Token', 'trust-wallet-token'],
             'ADAUP': ['ADAUP', 'adaup'],
             'MOB': ['MobileCoin', 'mobilecoin'],
             'CTK': ['Shentu', 'shentu'],
             'SAND': ['The Sandbox', 'the-sandbox'],
             'PROS': ['Prosper', 'prosper'],
             'CELO': ['Celo', 'celo'],
             'FLUX': ['Flux', 'flux'],
             'MATIC': ['Polygon', 'polygon'],
             'SRM': ['Serum', 'serum'],
             'XNO': ['Nano', 'nano'],
             'IMX': ['Immutable X', 'immutable-x'],
             'AVA': ['Travala.com', 'travala-com'],
             'PHB': ['PHB', 'phb'],
             'MANA': ['Decentraland', 'decentraland'],
             'MC': ['Merit Circle', 'merit-circle'],
             'GMT': ['Green Metaverse Token', 'green-metaverse-token'],
             'AUD': ['Australian Dollar', 'australian-dollar'],
             'MBOX': ['MOBOX', 'mobox'],
             'COCOS': ['Cocos-BCX', 'cocos-bcx'],
             'LIT': ['Litentry', 'litentry'],
             'MINA': ['Mina', 'mina'],
             'VGX': ['Voyager Token', 'voyager-token'],
             'BEL': ['Bella Protocol', 'bella-protocol'],
             '1INCH': ['1inch', '1inch'],
             'RAY': ['Raydium', 'raydium'],
             'PERP': ['Perpetual Protocol', 'perpetual-protocol'],
             'STG': ['Stargate Finance', 'stargate-finance'],
             'LOKA': ['League of Kingdoms', 'league-of-kingdoms'],
             'STRAX': ['Stratis', 'stratis'],
             'DREP': ['DREP', 'drep'],
             'HIVE': ['Hive', 'hive'],
             'PUNDIX': ['Pundi X', 'pundi-x'],
             'XRP': ['Ripple', 'ripple'],
             'FIDA': ['Bonfida', 'bonfida'],
             'POLS': ['Polkastarter', 'polkastarter'],
             'RNDR': ['Render Token', 'render-token'],
             'TOMO': ['TomoChain', 'tomochain'],
             'ENJ': ['Enjin Coin', 'enjin-coin'],
             'STORJ': ['Storj', 'storj'],
             'GLMR': ['Glimmer', 'glimmer'],
             'BNT': ['Bancor', 'bancor'],
             'ADA': ['Cardano', 'cardano'],
             'BICO': ['Biconomy', 'biconomy'],
             'DIA': ['DIA', 'dia'],
             'ARK': ['Ark', 'ark'],
             'UFT': ['UniLend', 'unilend'],
             'SFP': ['SafePal', 'safepal'],
             'ALGO': ['Algorand', 'algorand'],
             'C98': ['Coin98', 'coin98'],
             'SXP': ['Swipe', 'swipe'],
             'YGG': ['Yield Guild Games', 'yield-guild-games'],
             'CVP': ['PowerPool', 'powerpool'],
             'WTC': ['Walton', 'walton'],
             'ONG': ['Ontology Gas', 'ontology-gas'],
             'SNM': ['SONM', 'sonm'],
             'STX': ['Stacks', 'stacks'],
             'AGLD': ['Adventure Gold', 'adventure-gold'],
             'FIS': ['Stafi', 'stafi'],
             'PLA': ['PlayDapp', 'playdapp'],
             'BAT': ['Basic Attention Token', 'basic-attention-token'],
             'LRC': ['Loopring', 'loopring'],
             'ALPACA': ['Alpaca Finance', 'alpaca-finance'],
             'IOTA': ['IOTA', 'iota'],
             'GLM': ['Golem', 'golem'],
             'BSW': ['Biswap', 'biswap'],
             'VIDT': ['VIDT Datalink', 'vidt-datalink'],
             'VOXEL': ['Voxies', 'voxies'],
             'ZRX': ['0x', '0x'],
             'CHESS': ['Tranchess', 'tranchess'],
             'KMD': ['Komodo', 'komodo'],
             'TKO': ['Tokocrypto', 'tokocrypto'],
             'CHZ': ['Chiliz', 'chiliz'],
             'PNT': ['pNetwork', 'pnetwork'],
             'BAKE': ['BakeryToken', 'bakerytoken'],
             'POLY': ['Polymath', 'polymath'],
             'ICX': ['ICON', 'icon'],
             'XRPUP': ['XRPUP', 'xrpup'],
             'ONT': ['Ontology', 'ontology'],
             'FRONT': ['Frontier', 'frontier'],
             'FTM': ['Fantom', 'fantom'],
             'JOE': ['JOE', 'joe'],
             'STEEM': ['Steem', 'steem'],
             'TRIBE': ['Tribe', 'tribe'],
             'AUDIO': ['Audius', 'audius'],
             'DAR': ['Mines of Dalarnia', 'mines-of-dalarnia'],
             'WRX': ['WazirX', 'wazirx'],
             'MIR': ['Mirror Protocol', 'mirror-protocol'],
             'HARD': ['Kava Lend', 'kava-lend'],
             'NULS': ['Nuls', 'nuls'],
             'KLAY': ['Klaytn', 'klaytn'],
             'POWR': ['PowerLedger', 'powerledger'],
             'WAN': ['Wanchain', 'wanchain'],
             'BEAM': ['Beam', 'beam'],
             'ACA': ['Acala Token', 'acala-token'],
             'ADX': ['Ambire AdEx', 'ambire-adex'],
             'SYS': ['Syscoin', 'syscoin'],
             'ATA': ['Automata', 'automata'],
             'OCEAN': ['Ocean Protocol', 'ocean-protocol'],
             'DOTUP': ['DOTUP', 'dotup'],
             'RARE': ['SuperRare', 'superrare'],
             'CHR': ['Chromia', 'chromia'],
             'OGN': ['OriginToken', 'origintoken'],
             'CTSI': ['Cartesi', 'cartesi'],
             'WOO': ['WOO Network', 'woo-network'],
             'ELF': ['aelf', 'aelf'],
             'SUPER': ['SuperFarm', 'superfarm'],
             'CVC': ['Civic', 'civic'],
             'AERGO': ['Aergo', 'aergo'],
             'DODO': ['DODO', 'dodo'],
             'XLM': ['Stellar Lumens', 'stellar-lumens'],
             'DUSK': ['Dusk Network', 'dusk-network'],
             'FLM': ['Flamingo', 'flamingo'],
             'REN': ['REN', 'ren'],
             'ALPHA': ['Alpha Finance Lab', 'alpha-finance-lab'],
             'CTXC': ['Cortex', 'cortex'],
             'COTI': ['COTI', 'coti'],
             'BETA': ['Beta Finance', 'beta-finance'],
             'UTK': ['Utrust', 'utrust'],
             'REQ': ['Request Network', 'request-network'],
             'OXT': ['Orchid', 'orchid'],
             'GRT': ['The Graph', 'the-graph'],
             'ARDR': ['Ardor', 'ardor'],
             'NKN': ['NKN', 'nkn'],
             'PHA': ['Phala.Network', 'phala-network'],
             'ANC': ['Anchor Protocol', 'anchor-protocol'],
             'CLV': ['Clover Finance', 'clover-finance'],
             'BLZ': ['Bluzelle', 'bluzelle'],
             'WAXP': ['WAX', 'wax'],
             'FET': ['Fetch.AI', 'fetch-ai'],
             'VIB': ['Viberate', 'viberate'],
             'LTO': ['LTO Network', 'lto-network'],
             'IDEX': ['IDEX', 'idex'],
             'MDX': ['Mdex', 'mdex'],
             'DOGE': ['Dogecoin', 'dogecoin'],
             'ROSE': ['Oasis Network', 'oasis-network'],
             'TRX': ['TRON', 'tron'],
             'HBAR': ['Hedera Hashgraph', 'hedera-hashgraph'],
             'RIF': ['RSK Infrastructure Framework', 'rsk-infrastructure-framework'],
             'TFUEL': ['Theta Fuel', 'theta-fuel'],
             'LOOM': ['Loom Network', 'loom-network'],
             'TRXUP': ['TRXUP', 'trxup'],
             'TRU': ['TrueFi', 'truefi'],
             'FIO': ['FIO Protocol', 'fio-protocol'],
             'OM': ['MANTRA', 'mantra'],
             'STPT': ['Standard Tokenization Protocol', 'standard-tokenization-protocol'],
             'DNT': ['district0x', 'district0x'],
             'CFX': ['Conflux Network', 'conflux-network'],
             'BNBDOWN': ['BNBDOWN', 'bnbdown'],
             'XEM': ['NEM', 'nem'],
             'GALA': ['Gala', 'gala'],
             'SKL': ['SKALE Network', 'skale-network'],
             'AION': ['AION', 'aion'],
             'TVK': ['Virtua', 'virtua'],
             'ASTR': ['Astar', 'astar'],
             'RVN': ['Ravencoin', 'ravencoin'],
             'DF': ['dForce', 'dforce'],
             'BTCDOWN': ['BTCDOWN', 'btcdown'],
             'ARPA': ['ARPA Chain', 'arpa-chain'],
             'REI': ['REI Network', 'rei-network'],
             'DATA': ['Streamr', 'streamr'],
             'ZIL': ['Zilliqa', 'zilliqa'],
             'USTC': ['TerraClassicUSD', 'terraclassicusd'],
             'ANKR': ['ANKR', 'ankr'],
             'T': ['Threshold', 'threshold'],
             'IOTX': ['IoTeX', 'iotex'],
             'VITE': ['VITE', 'vite'],
             'MDT': ['Measurable Data Token', 'measurable-data-token'],
             'JST': ['JUST', 'just'],
             'TLM': ['Alien Worlds', 'alien-worlds'],
             'VET': ['VeChain', 'vechain'],
             'PEOPLE': ['ConstitutionDAO', 'constitutiondao'],
             'MITH': ['Mithril', 'mithril'],
             'PERL': ['Perlin', 'perlin'],
             'DOCK': ['DOCK', 'dock'],
             'GTO': ['Gifto', 'gifto'],
             'ONE': ['Harmony', 'harmony'],
             'FOR': ['ForTube', 'fortube'],
             'IRIS': ['IRISnet', 'irisnet'],
             'AMB': ['Ambrosus', 'ambrosus'],
             'CELR': ['Celer Network', 'celer-network'],
             'LINKUP': ['LINKUP', 'linkup'],
             'ACH': ['Alchemy Pay', 'alchemy-pay'],
             'IOST': ['IOST', 'iost'],
             'POND': ['Marlin', 'marlin'],
             'BTS': ['BitShares', 'bitshares'],
             'DGB': ['DigiByte', 'digibyte'],
             'QI': ['BENQI', 'benqi'],
             'RSR': ['Reserve Rights', 'reserve-rights'],
             'LINA': ['Linear', 'linear'],
             'FUN': ['FunToken', 'funtoken'],
             'STMX': ['StormX', 'stormx'],
             'TCT': ['TokenClub Token', 'tokenclub-token'],
             'JASMY': ['JasmyCoin', 'jasmycoin'],
             'COS': ['Contentos', 'contentos'],
             'LINKDOWN': ['LINKDOWN', 'linkdown'],
             'REEF': ['Reef', 'reef'],
             'SUN': ['SUN', 'sun'],
             'AMP': ['AMP', 'amp'],
             'OOKI': ['OokiDAO', 'ookidao'],
             'MFT': ['Mainframe', 'mainframe'],
             'ADADOWN': ['ADADOWN', 'adadown'],
             'IQ': ['Everipedia', 'everipedia'],
             'NBS': ['New BitShares', 'new-bitshares'],
             'KEY': ['Selfkey', 'selfkey'],
             'AKRO': ['Akropolis', 'akropolis'],
             'CKB': ['CKB', 'ckb'],
             'TROY': ['Troy', 'troy'],
             'SC': ['Siacoin', 'siacoin'],
             'MBL': ['MovieBloc', 'moviebloc'],
             'SLP': ['Smooth Love Potion', 'smooth-love-potion'],
             'XVG': ['Verge', 'verge'],
             'HOT': ['Holo', 'holo'],
             'LEVER': ['LEVER', 'lever'],
             'VTHO': ['VeThor Token', 'vethor-token'],
             'SPELL': ['Spell Token', 'spell-token'],
             'DENT': ['DENT', 'dent'],
             'EPX': ['Ellipsis', 'ellipsis'],
             'LUNC': ['Terra Classic', 'terra-classic'],
             'XRPDOWN': ['XRPDOWN', 'xrpdown'],
             'WIN': ['WINK', 'wink'],
             'XEC': ['eCash', 'ecash'],
             'OAX': ['openANX', 'openanx'],
             'PIVX': ['PIVX', 'pivx'],
             'SHIB': ['SHIBA INU', 'shiba-inu'],
             'WABI': ['TAEL', 'tael'],
             'AST': ['AirSwap', 'airswap'],
             'AGIX': ['SingularityNET Token', 'singularitynet-token'],
             'QLC': ['QLC Chain', 'qlc-chain'],
             'SNT': ['Status', 'status'],
             'BTTC': ['BitTorrent', 'bittorrent'],
             'QKC': ['QuarkChain', 'quarkchain']}
    return my_dict


def ticker_crypto_list():
    my_liste = ['1INCHBTC', '1INCHBUSD', '1INCHDOWNUSDT', '1INCHUPUSDT', '1INCHUSDT', 'AAVEBKRW', 'AAVEBNB', 'AAVEBRL',
               'AAVEBTC', 'AAVEBUSD', 'AAVEDOWNUSDT', 'AAVEETH', 'AAVEUPUSDT', 'AAVEUSDT', 'ACABTC', 'ACABUSD', 'ACAUSDT',
               'ACHBTC', 'ACHBUSD', 'ACHUSDT', 'ACMBTC', 'ACMBUSD', 'ACMUSDT', 'ADAAUD', 'ADABIDR', 'ADABKRW', 'ADABNB',
               'ADABRL', 'ADABTC', 'ADABUSD', 'ADADOWNUSDT', 'ADAETH', 'ADAEUR', 'ADAGBP', 'ADAPAX', 'ADARUB', 'ADATRY',
               'ADATUSD', 'ADAUPUSDT', 'ADAUSDC', 'ADAUSDT', 'ADXBNB', 'ADXBTC', 'ADXBUSD', 'ADXETH', 'ADXUSDT', 'AEBNB',
               'AEBTC', 'AEETH', 'AERGOBTC', 'AERGOBUSD', 'AGIBNB', 'AGIBTC', 'AGIETH', 'AGIXBTC', 'AGLDBNB', 'AGLDBTC',
               'AGLDBUSD', 'AGLDUSDT', 'AIONBNB', 'AIONBTC', 'AIONBUSD', 'AIONETH', 'AIONUSDT', 'AKROBTC', 'AKROBUSD',
               'AKROUSDT', 'ALCXBTC', 'ALCXBUSD', 'ALCXUSDT', 'ALGOBIDR', 'ALGOBNB', 'ALGOBTC', 'ALGOBUSD', 'ALGOETH',
               'ALGOPAX', 'ALGORUB', 'ALGOTRY', 'ALGOTUSD', 'ALGOUSDC', 'ALGOUSDT', 'ALICEBIDR', 'ALICEBNB', 'ALICEBTC',
               'ALICEBUSD', 'ALICETRY', 'ALICEUSDT', 'ALPACABNB', 'ALPACABTC', 'ALPACABUSD', 'ALPACAUSDT', 'ALPHABNB',
               'ALPHABTC', 'ALPHABUSD', 'ALPHAUSDT', 'ALPINEBTC', 'ALPINEBUSD', 'ALPINEEUR', 'ALPINETRY', 'ALPINEUSDT',
               'AMBBNB', 'AMBBTC', 'AMBBUSD', 'AMBETH', 'AMPBNB', 'AMPBTC', 'AMPBUSD', 'AMPUSDT', 'ANCBNB', 'ANCBTC',
               'ANCBUSD', 'ANCUSDT', 'ANKRBNB', 'ANKRBTC', 'ANKRBUSD', 'ANKRPAX', 'ANKRTRY', 'ANKRTUSD', 'ANKRUSDC',
               'ANKRUSDT', 'ANTBNB', 'ANTBTC', 'ANTBUSD', 'ANTUSDT', 'ANYBTC', 'ANYBUSD', 'ANYUSDT', 'APEAUD', 'APEBNB',
               'APEBRL', 'APEBTC', 'APEBUSD', 'APEETH', 'APEEUR', 'APEGBP', 'APETRY', 'APEUSDT', 'API3BNB', 'API3BTC',
               'API3BUSD', 'API3TRY', 'API3USDT', 'APPCBNB', 'APPCBTC', 'APPCETH', 'ARBNB', 'ARBTC', 'ARBUSD', 'ARDRBNB',
               'ARDRBTC', 'ARDRETH', 'ARDRUSDT', 'ARKBTC', 'ARKBUSD', 'ARKETH', 'ARNBTC', 'ARNETH', 'ARPABNB', 'ARPABTC',
               'ARPABUSD', 'ARPARUB', 'ARPATRY', 'ARPAUSDT', 'ARUSDT', 'ASRBTC', 'ASRBUSD', 'ASRUSDT', 'ASTBTC', 'ASTETH',
               'ASTRBTC', 'ASTRBUSD', 'ASTRETH', 'ASTRUSDT', 'ATABNB', 'ATABTC', 'ATABUSD', 'ATAUSDT', 'ATMBTC', 'ATMBUSD',
               'ATMUSDT', 'ATOMBIDR', 'ATOMBNB', 'ATOMBRL', 'ATOMBTC', 'ATOMBUSD', 'ATOMETH', 'ATOMEUR', 'ATOMPAX', 'ATOMTRY',
               'ATOMTUSD', 'ATOMUSDC', 'ATOMUSDT', 'AUCTIONBTC', 'AUCTIONBUSD', 'AUCTIONUSDT', 'AUDBUSD', 'AUDIOBTC', 'AUDIOBUSD',
               'AUDIOTRY', 'AUDIOUSDT', 'AUDUSDC', 'AUDUSDT', 'AUTOBTC', 'AUTOBUSD', 'AUTOUSDT', 'AVABNB', 'AVABTC', 'AVABUSD',
               'AVAUSDT', 'AVAXAUD', 'AVAXBIDR', 'AVAXBNB', 'AVAXBRL', 'AVAXBTC', 'AVAXBUSD', 'AVAXETH', 'AVAXEUR', 'AVAXGBP',
               'AVAXTRY', 'AVAXUSDT', 'AXSAUD', 'AXSBIDR', 'AXSBNB', 'AXSBRL', 'AXSBTC', 'AXSBUSD', 'AXSETH', 'AXSTRY', 'AXSUSDT',
               'BADGERBTC', 'BADGERBUSD', 'BADGERUSDT', 'BAKEBNB', 'BAKEBTC', 'BAKEBUSD', 'BAKEUSDT', 'BALBNB', 'BALBTC', 'BALBUSD',
               'BALUSDT', 'BANDBNB', 'BANDBTC', 'BANDBUSD', 'BANDUSDT', 'BARBTC', 'BARBUSD', 'BARUSDT', 'BATBNB', 'BATBTC',
               'BATBUSD', 'BATETH', 'BATPAX', 'BATTUSD', 'BATUSDC', 'BATUSDT', 'BCCBNB', 'BCCBTC', 'BCCETH', 'BCCUSDT',
               'BCDBTC', 'BCDETH', 'BCHABCBTC', 'BCHABCBUSD', 'BCHABCPAX', 'BCHABCTUSD', 'BCHABCUSDC', 'BCHABCUSDT',
               'BCHABUSD', 'BCHBNB', 'BCHBTC', 'BCHBUSD', 'BCHDOWNUSDT', 'BCHEUR', 'BCHPAX', 'BCHSVBTC', 'BCHSVPAX',
               'BCHSVTUSD', 'BCHSVUSDC', 'BCHSVUSDT', 'BCHTUSD', 'BCHUPUSDT', 'BCHUSDC', 'BCHUSDT', 'BCNBNB', 'BCNBTC',
               'BCNETH', 'BCPTBNB', 'BCPTBTC', 'BCPTETH', 'BCPTPAX', 'BCPTTUSD', 'BCPTUSDC', 'BDOTDOT', 'BEAMBNB',
               'BEAMBTC', 'BEAMUSDT', 'BEARBUSD', 'BEARUSDT', 'BELBNB', 'BELBTC', 'BELBUSD', 'BELETH', 'BELTRY',
               'BELUSDT', 'BETABNB', 'BETABTC', 'BETABUSD', 'BETAETH', 'BETAUSDT', 'BETHBUSD', 'BETHETH', 'BGBPUSDC',
               'BICOBTC', 'BICOBUSD', 'BICOUSDT', 'BIFIBNB', 'BIFIBUSD', 'BIFIUSDT', 'BKRWBUSD', 'BKRWUSDT', 'BLZBNB',
               'BLZBTC', 'BLZBUSD', 'BLZETH', 'BLZUSDT', 'BNBAUD', 'BNBBEARBUSD', 'BNBBEARUSDT', 'BNBBIDR', 'BNBBKRW',
               'BNBBRL', 'BNBBTC', 'BNBBULLBUSD', 'BNBBULLUSDT', 'BNBBUSD', 'BNBDAI', 'BNBDOWNUSDT', 'BNBETH', 'BNBEUR',
               'BNBGBP', 'BNBIDRT', 'BNBNGN', 'BNBPAX', 'BNBRUB', 'BNBTRY', 'BNBTUSD', 'BNBUAH', 'BNBUPUSDT', 'BNBUSDC',
               'BNBUSDP', 'BNBUSDS', 'BNBUSDT', 'BNBUST', 'BNBZAR', 'BNTBTC', 'BNTBUSD', 'BNTETH', 'BNTUSDT', 'BNXBNB',
               'BNXBTC', 'BNXBUSD', 'BNXUSDT', 'BONDBNB', 'BONDBTC', 'BONDBUSD', 'BONDETH', 'BONDUSDT', 'BOTBTC', 'BOTBUSD',
               'BQXBTC', 'BQXETH', 'BRDBNB', 'BRDBTC', 'BRDETH', 'BSWBNB', 'BSWBUSD', 'BSWETH', 'BSWTRY', 'BSWUSDT',
               'BTCAUD', 'BTCBBTC', 'BTCBIDR', 'BTCBKRW', 'BTCBRL', 'BTCBUSD', 'BTCDAI', 'BTCDOWNUSDT', 'BTCEUR', 'BTCGBP',
                'BTCIDRT', 'BTCNGN', 'BTCPAX', 'BTCRUB', 'BTCSTBTC', 'BTCSTBUSD', 'BTCSTUSDT', 'BTCTRY', 'BTCTUSD', 'BTCUAH',
                'BTCUPUSDT', 'BTCUSDC', 'BTCUSDP', 'BTCUSDS', 'BTCUSDT', 'BTCUST', 'BTCVAI', 'BTCZAR', 'BTGBTC', 'BTGBUSD',
                'BTGETH', 'BTGUSDT', 'BTSBNB', 'BTSBTC', 'BTSBUSD', 'BTSETH', 'BTSUSDT', 'BTTBNB', 'BTTBRL', 'BTTBTC', 'BTTBUSD',
                'BTTCBUSD', 'BTTCTRY', 'BTTCUSDC', 'BTTCUSDT', 'BTTEUR', 'BTTPAX', 'BTTTRX', 'BTTTRY', 'BTTTUSD',
                'BTTUSDC', 'BTTUSDT', 'BULLBUSD', 'BULLUSDT', 'BURGERBNB', 'BURGERBUSD', 'BURGERETH', 'BURGERUSDT',
                'BUSDBIDR', 'BUSDBKRW', 'BUSDBRL', 'BUSDBVND', 'BUSDDAI', 'BUSDIDRT', 'BUSDNGN', 'BUSDRUB', 'BUSDTRY',
                'BUSDUAH', 'BUSDUSDT', 'BUSDVAI', 'BUSDZAR', 'BZRXBNB', 'BZRXBTC', 'BZRXBUSD', 'BZRXUSDT', 'C98BNB', 'C98BRL', 'C98BTC', 'C98BUSD', 'C98USDT', 'CAKEAUD', 'CAKEBNB', 'CAKEBRL', 'CAKEBTC', 'CAKEBUSD', 'CAKEGBP', 'CAKEUSDT', 'CDTBTC', 'CDTETH', 'CELOBTC', 'CELOBUSD', 'CELOUSDT', 'CELRBNB', 'CELRBTC', 'CELRBUSD', 'CELRETH', 'CELRUSDT', 'CFXBTC', 'CFXBUSD', 'CFXUSDT', 'CHATBTC', 'CHATETH', 'CHESSBNB', 'CHESSBTC', 'CHESSBUSD', 'CHESSUSDT', 'CHRBNB', 'CHRBTC', 'CHRBUSD', 'CHRETH', 'CHRUSDT', 'CHZBNB', 'CHZBRL', 'CHZBTC', 'CHZBUSD', 'CHZEUR', 'CHZGBP', 'CHZTRY', 'CHZUSDT', 'CITYBNB', 'CITYBTC', 'CITYBUSD', 'CITYUSDT', 'CKBBTC', 'CKBBUSD', 'CKBUSDT', 'CLOAKBTC', 'CLOAKETH', 'CLVBNB', 'CLVBTC', 'CLVBUSD', 'CLVUSDT', 'CMTBNB', 'CMTBTC', 'CMTETH', 'CNDBNB', 'CNDBTC', 'CNDETH', 'COCOSBNB', 'COCOSBTC', 'COCOSBUSD', 'COCOSTRY', 'COCOSUSDT', 'COMPBNB', 'COMPBTC', 'COMPBUSD', 'COMPUSDT', 'COSBNB', 'COSBTC', 'COSBUSD', 'COSTRY', 'COSUSDT', 'COTIBNB', 'COTIBTC', 'COTIBUSD', 'COTIUSDT', 'COVERBUSD', 'COVERETH', 'CREAMBNB', 'CREAMBUSD', 'CRVBNB', 'CRVBTC', 'CRVBUSD', 'CRVETH', 'CRVUSDT', 'CTKBNB', 'CTKBTC', 'CTKBUSD', 'CTKUSDT', 'CTSIBNB', 'CTSIBTC', 'CTSIBUSD', 'CTSIUSDT', 'CTXCBNB', 'CTXCBTC', 'CTXCBUSD', 'CTXCUSDT', 'CVCBNB', 'CVCBTC', 'CVCBUSD', 'CVCETH', 'CVCUSDT', 'CVPBUSD', 'CVPETH', 'CVPUSDT', 'CVXBTC', 'CVXBUSD', 'CVXUSDT', 'DAIBNB', 'DAIBTC', 'DAIBUSD', 'DAIUSDT', 'DARBNB', 'DARBTC', 'DARBUSD', 'DARETH', 'DAREUR', 'DARTRY', 'DARUSDT', 'DASHBNB', 'DASHBTC', 'DASHBUSD', 'DASHETH', 'DASHUSDT', 'DATABTC', 'DATABUSD', 'DATAETH', 'DATAUSDT', 'DCRBNB', 'DCRBTC', 'DCRBUSD', 'DCRUSDT', 'DEGOBTC', 'DEGOBUSD', 'DEGOUSDT', 'DENTBTC', 'DENTBUSD', 'DENTETH', 'DENTTRY', 'DENTUSDT', 'DEXEBUSD', 'DEXEETH', 'DEXEUSDT', 'DFBUSD', 'DFETH', 'DFUSDT', 'DGBBTC', 'DGBBUSD', 'DGBUSDT', 'DGDBTC', 'DGDETH', 'DIABNB', 'DIABTC', 'DIABUSD', 'DIAUSDT', 'DLTBNB', 'DLTBTC', 'DLTETH', 'DNTBTC', 'DNTBUSD', 'DNTETH', 'DNTUSDT', 'DOCKBTC', 'DOCKBUSD', 'DOCKETH', 'DOCKUSDT', 'DODOBTC', 'DODOBUSD', 'DODOUSDT', 'DOGEAUD', 'DOGEBIDR', 'DOGEBNB', 'DOGEBRL', 'DOGEBTC', 'DOGEBUSD', 'DOGEEUR', 'DOGEGBP', 'DOGEPAX', 'DOGERUB', 'DOGETRY', 'DOGEUSDC', 'DOGEUSDT', 'DOTAUD', 'DOTBIDR', 'DOTBKRW', 'DOTBNB', 'DOTBRL', 'DOTBTC', 'DOTBUSD', 'DOTDOWNUSDT', 'DOTETH', 'DOTEUR', 'DOTGBP', 'DOTNGN', 'DOTRUB', 'DOTTRY', 'DOTUPUSDT', 'DOTUSDT', 'DREPBNB', 'DREPBTC', 'DREPBUSD', 'DREPUSDT', 'DUSKBNB', 'DUSKBTC', 'DUSKBUSD', 'DUSKPAX', 'DUSKUSDC', 'DUSKUSDT', 'DYDXBNB', 'DYDXBTC', 'DYDXBUSD', 'DYDXETH', 'DYDXUSDT', 'EASYBTC', 'EASYETH', 'EDOBTC', 'EDOETH', 'EGLDBNB', 'EGLDBTC', 'EGLDBUSD', 'EGLDETH', 'EGLDEUR', 'EGLDUSDT', 'ELFBTC', 'ELFBUSD', 'ELFETH', 'ELFUSDT', 'ENGBTC', 'ENGETH', 'ENJBNB', 'ENJBRL', 'ENJBTC', 'ENJBUSD', 'ENJETH', 'ENJEUR', 'ENJGBP', 'ENJTRY', 'ENJUSDT', 'ENSBNB', 'ENSBTC', 'ENSBUSD', 'ENSTRY', 'ENSUSDT', 'EOSAUD', 'EOSBEARBUSD', 'EOSBEARUSDT', 'EOSBNB', 'EOSBTC', 'EOSBULLBUSD', 'EOSBULLUSDT', 'EOSBUSD', 'EOSDOWNUSDT', 'EOSETH', 'EOSEUR', 'EOSPAX', 'EOSTRY', 'EOSTUSD', 'EOSUPUSDT', 'EOSUSDC', 'EOSUSDT', 'EPSBTC', 'EPSBUSD', 'EPSUSDT', 'EPXBUSD', 'EPXUSDT', 'ERDBNB', 'ERDBTC', 'ERDBUSD', 'ERDPAX', 'ERDUSDC', 'ERDUSDT', 'ERNBNB', 'ERNBUSD', 'ERNUSDT', 'ETCBNB', 'ETCBRL', 'ETCBTC', 'ETCBUSD', 'ETCETH', 'ETCEUR', 'ETCGBP', 'ETCPAX', 'ETCTRY', 'ETCTUSD', 'ETCUSDC', 'ETCUSDT', 'ETHAUD', 'ETHBEARBUSD', 'ETHBEARUSDT', 'ETHBIDR', 'ETHBKRW', 'ETHBRL', 'ETHBTC', 'ETHBULLBUSD', 'ETHBULLUSDT', 'ETHBUSD', 'ETHDAI', 'ETHDOWNUSDT', 'ETHEUR', 'ETHGBP', 'ETHNGN', 'ETHPAX', 'ETHRUB', 'ETHTRY', 'ETHTUSD', 'ETHUAH', 'ETHUPUSDT', 'ETHUSDC', 'ETHUSDP', 'ETHUSDT', 'ETHUST', 'ETHZAR', 'EURBUSD', 'EURUSDT', 'EVXBTC', 'EVXETH', 'EZBTC', 'EZETH', 'FARMBNB', 'FARMBTC', 'FARMBUSD', 'FARMETH', 'FARMUSDT', 'FETBNB', 'FETBTC', 'FETBUSD', 'FETUSDT', 'FIDABNB', 'FIDABTC', 'FIDABUSD', 'FIDAUSDT', 'FILBNB', 'FILBTC', 'FILBUSD', 'FILDOWNUSDT', 'FILETH', 'FILTRY', 'FILUPUSDT', 'FILUSDT', 'FIOBNB', 'FIOBTC', 'FIOBUSD', 'FIOUSDT', 'FIROBTC', 'FIROBUSD', 'FIROETH', 'FIROUSDT', 'FISBIDR', 'FISBRL', 'FISBTC', 'FISBUSD', 'FISTRY', 'FISUSDT', 'FLMBNB', 'FLMBTC', 'FLMBUSD', 'FLMUSDT', 'FLOWBNB', 'FLOWBTC', 'FLOWBUSD', 'FLOWUSDT', 'FLUXBTC', 'FLUXBUSD', 'FLUXUSDT', 'FORBNB', 'FORBTC', 'FORBUSD', 'FORTHBTC', 'FORTHBUSD', 'FORTHUSDT', 'FORUSDT', 'FRONTBTC', 'FRONTBUSD', 'FRONTETH', 'FRONTUSDT', 'FTMAUD', 'FTMBIDR', 'FTMBNB', 'FTMBRL', 'FTMBTC', 'FTMBUSD', 'FTMETH', 'FTMEUR', 'FTMPAX', 'FTMRUB', 'FTMTRY', 'FTMTUSD', 'FTMUSDC', 'FTMUSDT', 'FTTBNB', 'FTTBTC', 'FTTBUSD', 'FTTETH', 'FTTUSDT', 'FUELBTC', 'FUELETH', 'FUNBNB', 'FUNBTC', 'FUNETH', 'FUNUSDT', 'FXSBTC', 'FXSBUSD', 'FXSUSDT', 'GALAAUD', 'GALABNB', 'GALABRL', 'GALABTC', 'GALABUSD', 'GALAETH', 'GALAEUR', 'GALATRY', 'GALAUSDT', 'GALBNB', 'GALBRL', 'GALBTC', 'GALBUSD', 'GALETH', 'GALEUR', 'GALTRY', 'GALUSDT', 'GASBTC', 'GASBUSD', 'GBPBUSD', 'GBPUSDT', 'GHSTBUSD', 'GHSTETH', 'GHSTUSDT', 'GLMBTC', 'GLMBUSD', 'GLMETH', 'GLMRBNB', 'GLMRBTC', 'GLMRBUSD', 'GLMRUSDT', 'GMTAUD', 'GMTBNB', 'GMTBRL', 'GMTBTC', 'GMTBUSD', 'GMTETH', 'GMTEUR', 'GMTGBP', 'GMTTRY', 'GMTUSDT', 'GNOBNB', 'GNOBTC', 'GNOBUSD', 'GNOUSDT', 'GNTBNB', 'GNTBTC', 'GNTETH', 'GOBNB', 'GOBTC', 'GRSBTC', 'GRSETH', 'GRTBTC', 'GRTBUSD', 'GRTETH', 'GRTEUR', 'GRTTRY', 'GRTUSDT', 'GTCBNB', 'GTCBTC', 'GTCBUSD', 'GTCUSDT', 'GTOBNB', 'GTOBTC', 'GTOBUSD', 'GTOETH', 'GTOPAX', 'GTOTUSD', 'GTOUSDC', 'GTOUSDT', 'GVTBTC', 'GVTETH', 'GXSBNB', 'GXSBTC', 'GXSETH', 'GXSUSDT', 'HARDBNB', 'HARDBTC', 'HARDBUSD', 'HARDUSDT', 'HBARBNB', 'HBARBTC', 'HBARBUSD', 'HBARUSDT', 'HCBTC', 'HCETH', 'HCUSDT', 'HEGICBUSD', 'HEGICETH', 'HIGHBNB', 'HIGHBTC', 'HIGHBUSD', 'HIGHUSDT', 'HIVEBNB', 'HIVEBTC', 'HIVEBUSD', 'HIVEUSDT', 'HNTBTC', 'HNTBUSD', 'HNTUSDT', 'HOTBNB', 'HOTBRL', 'HOTBTC', 'HOTBUSD', 'HOTETH', 'HOTEUR', 'HOTTRY', 'HOTUSDT', 'HSRBTC', 'HSRETH', 'ICNBTC', 'ICNETH', 'ICPBNB', 'ICPBTC', 'ICPBUSD', 'ICPETH', 'ICPEUR', 'ICPRUB', 'ICPTRY', 'ICPUSDT', 'ICXBNB', 'ICXBTC', 'ICXBUSD', 'ICXETH', 'ICXUSDT', 'IDEXBNB', 'IDEXBTC', 'IDEXBUSD', 'IDEXUSDT', 'ILVBNB', 'ILVBTC', 'ILVBUSD', 'ILVUSDT', 'IMXBNB', 'IMXBTC', 'IMXBUSD', 'IMXUSDT', 'INJBNB', 'INJBTC', 'INJBUSD', 'INJTRY', 'INJUSDT', 'INSBTC', 'INSETH', 'IOSTBTC', 'IOSTBUSD', 'IOSTETH', 'IOSTUSDT', 'IOTABNB', 'IOTABTC', 'IOTABUSD', 'IOTAETH', 'IOTAUSDT', 'IOTXBTC', 'IOTXBUSD', 'IOTXETH', 'IOTXUSDT', 'IQBNB', 'IQBUSD', 'IRISBNB', 'IRISBTC', 'IRISBUSD', 'IRISUSDT', 'JASMYBNB', 'JASMYBTC', 'JASMYBUSD', 'JASMYETH', 'JASMYEUR', 'JASMYTRY', 'JASMYUSDT', 'JOEBTC', 'JOEBUSD', 'JOEUSDT', 'JSTBNB', 'JSTBTC', 'JSTBUSD', 'JSTUSDT', 'JUVBTC', 'JUVBUSD', 'JUVUSDT', 'KAVABNB', 'KAVABTC', 'KAVABUSD', 'KAVAETH', 'KAVAUSDT', 'KDABTC', 'KDABUSD', 'KDAUSDT', 'KEEPBNB', 'KEEPBTC', 'KEEPBUSD', 'KEEPUSDT', 'KEYBTC', 'KEYBUSD', 'KEYETH', 'KEYUSDT', 'KLAYBNB', 'KLAYBTC', 'KLAYBUSD', 'KLAYUSDT', 'KMDBTC', 'KMDBUSD', 'KMDETH', 'KMDUSDT', 'KNCBNB', 'KNCBTC', 'KNCBUSD', 'KNCETH', 'KNCUSDT', 'KP3RBNB', 'KP3RBUSD', 'KP3RUSDT', 'KSMAUD', 'KSMBNB', 'KSMBTC', 'KSMBUSD', 'KSMETH', 'KSMUSDT', 'LAZIOBTC', 'LAZIOBUSD', 'LAZIOEUR', 'LAZIOTRY', 'LAZIOUSDT', 'LDOBTC', 'LDOBUSD', 'LDOUSDT', 'LENDBKRW', 'LENDBTC', 'LENDBUSD', 'LENDETH', 'LENDUSDT', 'LEVERBUSD', 'LEVERUSDT', 'LINABNB', 'LINABTC', 'LINABUSD', 'LINAUSDT', 'LINKAUD', 'LINKBKRW', 'LINKBNB', 'LINKBRL', 'LINKBTC', 'LINKBUSD', 'LINKDOWNUSDT', 'LINKETH', 'LINKEUR', 'LINKGBP', 'LINKNGN', 'LINKPAX', 'LINKTRY', 'LINKTUSD', 'LINKUPUSDT', 'LINKUSDC', 'LINKUSDT', 'LITBTC', 'LITBUSD', 'LITETH', 'LITUSDT', 'LOKABNB', 'LOKABTC', 'LOKABUSD', 'LOKAUSDT', 'LOOMBNB', 'LOOMBTC', 'LOOMBUSD', 'LOOMETH', 'LPTBNB', 'LPTBTC', 'LPTBUSD', 'LPTUSDT', 'LRCBNB', 'LRCBTC', 'LRCBUSD', 'LRCETH', 'LRCTRY', 'LRCUSDT', 'LSKBNB', 'LSKBTC', 'LSKBUSD', 'LSKETH', 'LSKUSDT', 'LTCBNB', 'LTCBRL', 'LTCBTC', 'LTCBUSD', 'LTCDOWNUSDT', 'LTCETH', 'LTCEUR', 'LTCGBP', 'LTCNGN', 'LTCPAX', 'LTCRUB', 'LTCTUSD', 'LTCUAH', 'LTCUPUSDT', 'LTCUSDC', 'LTCUSDT', 'LTOBNB', 'LTOBTC', 'LTOBUSD', 'LTOUSDT', 'LUNAAUD', 'LUNABIDR', 'LUNABNB', 'LUNABRL', 'LUNABTC', 'LUNABUSD', 'LUNAETH', 'LUNAEUR', 'LUNAGBP', 'LUNATRY', 'LUNAUSDT', 'LUNAUST', 'LUNBTC', 'LUNCBUSD', 'LUNCUSDT', 'LUNETH', 'MANABIDR', 'MANABNB', 'MANABRL', 'MANABTC', 'MANABUSD', 'MANAETH', 'MANATRY', 'MANAUSDT', 'MASKBNB', 'MASKBUSD', 'MASKUSDT', 'MATICAUD', 'MATICBIDR', 'MATICBNB', 'MATICBRL', 'MATICBTC', 'MATICBUSD', 'MATICETH', 'MATICEUR', 'MATICGBP', 'MATICRUB', 'MATICTRY', 'MATICUSDT', 'MBLBNB', 'MBLBTC', 'MBLBUSD', 'MBLUSDT', 'MBOXBNB', 'MBOXBTC', 'MBOXBUSD', 'MBOXTRY', 'MBOXUSDT', 'MCBNB', 'MCBTC', 'MCBUSD', 'MCOBNB', 'MCOBTC', 'MCOETH', 'MCOUSDT', 'MCUSDT', 'MDABTC', 'MDAETH', 'MDTBNB', 'MDTBTC', 'MDTBUSD', 'MDTUSDT', 'MDXBNB', 'MDXBTC', 'MDXBUSD', 'MDXUSDT', 'MFTBNB', 'MFTBTC', 'MFTETH', 'MFTUSDT', 'MINABNB', 'MINABTC', 'MINABUSD', 'MINATRY', 'MINAUSDT', 'MIRBTC', 'MIRBUSD', 'MIRUSDT', 'MITHBNB', 'MITHBTC', 'MITHUSDT', 'MKRBNB', 'MKRBTC', 'MKRBUSD', 'MKRUSDT', 'MLNBNB', 'MLNBTC', 'MLNBUSD', 'MLNUSDT', 'MOBBTC', 'MOBBUSD', 'MOBUSDT', 'MODBTC', 'MODETH', 'MOVRBNB', 'MOVRBTC', 'MOVRBUSD', 'MOVRUSDT', 'MTHBTC', 'MTHETH', 'MTLBTC', 'MTLBUSD', 'MTLETH', 'MTLUSDT', 'MULTIBTC', 'MULTIBUSD', 'MULTIUSDT', 'NANOBNB', 'NANOBTC', 'NANOBUSD', 'NANOETH', 'NANOUSDT', 'NASBNB', 'NASBTC', 'NASETH', 'NAVBNB', 'NAVBTC', 'NAVETH', 'NBSBTC', 'NBSUSDT', 'NBTBIDR', 'NBTUSDT', 'NCASHBNB', 'NCASHBTC', 'NCASHETH', 'NEARBNB', 'NEARBTC', 'NEARBUSD', 'NEARETH', 'NEAREUR', 'NEARRUB', 'NEARTRY', 'NEARUSDT', 'NEBLBNB', 'NEBLBTC', 'NEBLBUSD', 'NEOBNB', 'NEOBTC', 'NEOBUSD', 'NEOETH', 'NEOPAX', 'NEORUB', 'NEOTRY', 'NEOTUSD', 'NEOUSDC', 'NEOUSDT', 'NEXOBTC', 'NEXOBUSD', 'NEXOUSDT', 'NKNBNB', 'NKNBTC', 'NKNBUSD', 'NKNUSDT', 'NMRBTC', 'NMRBUSD', 'NMRUSDT', 'NPXSBTC', 'NPXSETH', 'NPXSUSDC', 'NPXSUSDT', 'NUAUD', 'NUBNB', 'NUBTC', 'NUBUSD', 'NULSBNB', 'NULSBTC', 'NULSBUSD', 'NULSETH', 'NULSUSDT', 'NURUB', 'NUUSDT', 'NXSBNB', 'NXSBTC', 'NXSETH', 'OAXBTC', 'OAXETH', 'OCEANBNB', 'OCEANBTC', 'OCEANBUSD', 'OCEANUSDT', 'OGBTC', 'OGBUSD', 'OGNBNB', 'OGNBTC', 'OGNBUSD', 'OGNUSDT', 'OGUSDT', 'OMBTC', 'OMBUSD', 'OMGBNB', 'OMGBTC', 'OMGBUSD', 'OMGETH', 'OMGUSDT', 'OMUSDT', 'ONEBIDR', 'ONEBNB', 'ONEBTC', 'ONEBUSD', 'ONEETH', 'ONEPAX', 'ONETRY', 'ONETUSD', 'ONEUSDC', 'ONEUSDT', 'ONGBNB', 'ONGBTC', 'ONGUSDT', 'ONTBNB', 'ONTBTC', 'ONTBUSD', 'ONTETH', 'ONTPAX', 'ONTTRY', 'ONTUSDC', 'ONTUSDT', 'OOKIBNB', 'OOKIBUSD', 'OOKIETH', 'OOKIUSDT', 'OPBNB', 'OPBTC', 'OPBUSD', 'OPETH', 'OPEUR', 'OPUSDT', 'ORNBTC', 'ORNBUSD', 'ORNUSDT', 'OSTBNB', 'OSTBTC', 'OSTETH', 'OXTBTC', 'OXTBUSD', 'OXTUSDT', 'PAXBNB', 'PAXBTC', 'PAXBUSD', 'PAXETH', 'PAXGBNB', 'PAXGBTC', 'PAXGBUSD', 'PAXGUSDT', 'PAXTUSD', 'PAXUSDT', 'PEOPLEBNB', 'PEOPLEBTC', 'PEOPLEBUSD', 'PEOPLEETH', 'PEOPLEUSDT', 'PERLBNB', 'PERLBTC', 'PERLUSDC', 'PERLUSDT', 'PERPBTC', 'PERPBUSD', 'PERPUSDT', 'PHABTC', 'PHABUSD', 'PHAUSDT', 'PHBBNB', 'PHBBTC', 'PHBBUSD', 'PHBPAX', 'PHBTUSD', 'PHBUSDC', 'PHXBNB', 'PHXBTC', 'PHXETH', 'PIVXBNB', 'PIVXBTC', 'PLABNB', 'PLABTC', 'PLABUSD', 'PLAUSDT', 'PNTBTC', 'PNTUSDT', 'POABNB', 'POABTC', 'POAETH', 'POEBTC', 'POEETH', 'POLSBNB', 'POLSBTC', 'POLSBUSD', 'POLSUSDT', 'POLYBNB', 'POLYBTC', 'POLYBUSD', 'POLYUSDT', 'PONDBTC', 'PONDBUSD', 'PONDUSDT', 'PORTOBTC', 'PORTOBUSD', 'PORTOEUR', 'PORTOTRY', 'PORTOUSDT', 'POWRBNB', 'POWRBTC', 'POWRBUSD', 'POWRETH', 'POWRUSDT', 'PPTBTC', 'PPTETH', 'PROMBNB', 'PROMBTC', 'PROMBUSD', 'PROSBUSD', 'PROSETH', 'PSGBTC', 'PSGBUSD', 'PSGUSDT', 'PUNDIXBUSD', 'PUNDIXETH', 'PUNDIXUSDT', 'PYRBTC', 'PYRBUSD', 'PYRUSDT', 'QIBNB', 'QIBTC', 'QIBUSD', 'QIUSDT', 'QKCBTC', 'QKCETH', 'QLCBNB', 'QLCBTC', 'QLCETH', 'QNTBNB', 'QNTBTC', 'QNTBUSD', 'QNTUSDT', 'QSPBNB', 'QSPBTC', 'QSPETH', 'QTUMBNB', 'QTUMBTC', 'QTUMBUSD', 'QTUMETH', 'QTUMUSDT', 'QUICKBNB', 'QUICKBTC', 'QUICKBUSD', 'QUICKUSDT', 'RADBNB', 'RADBTC', 'RADBUSD', 'RADUSDT', 'RAMPBTC', 'RAMPBUSD', 'RAMPUSDT', 'RAREBNB', 'RAREBTC', 'RAREBUSD', 'RAREUSDT', 'RAYBNB', 'RAYBUSD', 'RAYUSDT', 'RCNBNB', 'RCNBTC', 'RCNETH', 'RDNBNB', 'RDNBTC', 'RDNETH', 'REEFBIDR', 'REEFBTC', 'REEFBUSD', 'REEFTRY', 'REEFUSDT', 'REIBNB', 'REIBUSD', 'REIETH', 'REIUSDT', 'RENBNB', 'RENBTC', 'RENBTCBTC', 'RENBTCETH', 'RENBUSD', 'RENUSDT', 'REPBNB', 'REPBTC', 'REPBUSD', 'REPUSDT', 'REQBTC', 'REQBUSD', 'REQETH', 'REQUSDT', 'RGTBNB', 'RGTBTC', 'RGTBUSD', 'RGTUSDT', 'RIFBTC', 'RIFUSDT', 'RLCBNB', 'RLCBTC', 'RLCBUSD', 'RLCETH', 'RLCUSDT', 'RNDRBTC', 'RNDRBUSD', 'RNDRUSDT', 'ROSEBNB', 'ROSEBTC', 'ROSEBUSD', 'ROSEETH', 'ROSETRY', 'ROSEUSDT', 'RPXBNB', 'RPXBTC', 'RPXETH', 'RSRBNB', 'RSRBTC', 'RSRBUSD', 'RSRUSDT', 'RUNEAUD', 'RUNEBNB', 'RUNEBTC', 'RUNEBUSD', 'RUNEETH', 'RUNEEUR', 'RUNEGBP', 'RUNETRY', 'RUNEUSDT', 'RVNBTC', 'RVNBUSD', 'RVNTRY', 'RVNUSDT', 'SALTBTC', 'SALTETH', 'SANDAUD', 'SANDBIDR', 'SANDBNB', 'SANDBRL', 'SANDBTC', 'SANDBUSD', 'SANDETH', 'SANDTRY', 'SANDUSDT', 'SANTOSBRL', 'SANTOSBTC', 'SANTOSBUSD', 'SANTOSTRY', 'SANTOSUSDT', 'SCBTC', 'SCBUSD', 'SCETH', 'SCRTBTC', 'SCRTBUSD', 'SCRTETH', 'SCRTUSDT', 'SCUSDT', 'SFPBTC', 'SFPBUSD', 'SFPUSDT', 'SHIBAUD', 'SHIBBRL', 'SHIBBUSD', 'SHIBDOGE', 'SHIBEUR', 'SHIBGBP', 'SHIBRUB', 'SHIBTRY', 'SHIBUAH', 'SHIBUSDT', 'SKLBTC', 'SKLBUSD', 'SKLUSDT', 'SKYBNB', 'SKYBTC', 'SKYETH', 'SLPBIDR', 'SLPBNB', 'SLPBUSD', 'SLPETH', 'SLPTRY', 'SLPUSDT', 'SNGLSBTC', 'SNGLSETH', 'SNMBTC', 'SNMBUSD', 'SNMETH', 'SNTBTC', 'SNTETH', 'SNXBNB', 'SNXBTC', 'SNXBUSD', 'SNXETH', 'SNXUSDT', 'SOLAUD', 'SOLBIDR', 'SOLBNB', 'SOLBRL', 'SOLBTC', 'SOLBUSD', 'SOLETH', 'SOLEUR', 'SOLGBP', 'SOLRUB', 'SOLTRY', 'SOLUSDC', 'SOLUSDT', 'SPARTABNB', 'SPELLBNB', 'SPELLBTC', 'SPELLBUSD', 'SPELLTRY', 'SPELLUSDT', 'SRMBIDR', 'SRMBNB', 'SRMBTC', 'SRMBUSD', 'SRMUSDT', 'SSVBTC', 'SSVBUSD', 'SSVETH', 'STEEMBNB', 'STEEMBTC', 'STEEMBUSD', 'STEEMETH', 'STEEMUSDT', 'STGBTC', 'STGBUSD', 'STGUSDT', 'STMXBTC', 'STMXBUSD', 'STMXETH', 'STMXUSDT', 'STORJBTC', 'STORJBUSD', 'STORJETH', 'STORJTRY', 'STORJUSDT', 'STORMBNB', 'STORMBTC', 'STORMETH', 'STORMUSDT', 'STPTBNB', 'STPTBTC', 'STPTBUSD', 'STPTUSDT', 'STRATBNB', 'STRATBTC', 'STRATBUSD', 'STRATETH', 'STRATUSDT', 'STRAXBTC', 'STRAXBUSD', 'STRAXETH', 'STRAXUSDT', 'STXBNB', 'STXBTC', 'STXBUSD', 'STXUSDT', 'SUBBTC', 'SUBETH', 'SUNBTC', 'SUNBUSD', 'SUNUSDT', 'SUPERBTC', 'SUPERBUSD', 'SUPERUSDT', 'SUSDBTC', 'SUSDETH', 'SUSDUSDT', 'SUSHIBNB', 'SUSHIBTC', 'SUSHIBUSD', 'SUSHIDOWNUSDT', 'SUSHIUPUSDT', 'SUSHIUSDT', 'SWRVBNB', 'SWRVBUSD', 'SXPAUD', 'SXPBIDR', 'SXPBNB', 'SXPBTC', 'SXPBUSD', 'SXPDOWNUSDT', 'SXPEUR', 'SXPGBP', 'SXPTRY', 'SXPUPUSDT', 'SXPUSDT', 'SYSBNB', 'SYSBTC', 'SYSBUSD', 'SYSETH', 'SYSUSDT', 'TBUSD', 'TCTBNB', 'TCTBTC', 'TCTUSDT', 'TFUELBNB', 'TFUELBTC', 'TFUELBUSD', 'TFUELPAX', 'TFUELTUSD', 'TFUELUSDC', 'TFUELUSDT', 'THETABNB', 'THETABTC', 'THETABUSD', 'THETAETH', 'THETAEUR', 'THETAUSDT', 'TKOBIDR', 'TKOBTC', 'TKOBUSD', 'TKOUSDT', 'TLMBNB', 'TLMBTC', 'TLMBUSD', 'TLMTRY', 'TLMUSDT', 'TNBBTC', 'TNBETH', 'TNTBTC', 'TNTETH', 'TOMOBNB', 'TOMOBTC', 'TOMOBUSD', 'TOMOUSDC', 'TOMOUSDT', 'TORNBNB', 'TORNBTC', 'TORNBUSD', 'TORNUSDT', 'TRBBNB', 'TRBBTC', 'TRBBUSD', 'TRBUSDT', 'TRIBEBNB', 'TRIBEBTC', 'TRIBEBUSD', 'TRIBEUSDT', 'TRIGBNB', 'TRIGBTC', 'TRIGETH', 'TROYBNB', 'TROYBTC', 'TROYBUSD', 'TROYUSDT', 'TRUBTC', 'TRUBUSD', 'TRURUB', 'TRUUSDT', 'TRXAUD', 'TRXBNB', 'TRXBTC', 'TRXBUSD', 'TRXDOWNUSDT', 'TRXETH', 'TRXEUR', 'TRXNGN', 'TRXPAX', 'TRXTRY', 'TRXTUSD', 'TRXUPUSDT', 'TRXUSDC', 'TRXUSDT', 'TRXXRP', 'TUSDBNB', 'TUSDBTC', 'TUSDBTUSD', 'TUSDBUSD', 'TUSDETH', 'TUSDT', 'TUSDUSDT', 'TVKBTC', 'TVKBUSD', 'TVKUSDT', 'TWTBTC', 'TWTBUSD', 'TWTTRY', 'TWTUSDT', 'UFTBUSD', 'UFTETH', 'UMABTC', 'UMABUSD', 'UMATRY', 'UMAUSDT', 'UNFIBNB', 'UNFIBTC', 'UNFIBUSD', 'UNFIETH', 'UNFIUSDT', 'UNIAUD', 'UNIBNB', 'UNIBTC', 'UNIBUSD', 'UNIDOWNUSDT', 'UNIETH', 'UNIEUR', 'UNIUPUSDT', 'UNIUSDT', 'USDCBNB', 'USDCBUSD', 'USDCPAX', 'USDCTUSD', 'USDCUSDT', 'USDPBUSD', 'USDPUSDT', 'USDSBUSDS', 'USDSBUSDT', 'USDSPAX', 'USDSTUSD', 'USDSUSDC', 'USDSUSDT', 'USDTBIDR', 'USDTBKRW', 'USDTBRL', 'USDTBVND', 'USDTDAI', 'USDTIDRT', 'USDTNGN', 'USDTRUB', 'USDTTRY', 'USDTUAH', 'USDTZAR', 'USTBTC', 'USTBUSD', 'USTCBUSD', 'USTUSDT', 'UTKBTC', 'UTKBUSD', 'UTKUSDT', 'VENBNB', 'VENBTC', 'VENETH', 'VENUSDT', 'VETBNB', 'VETBTC', 'VETBUSD', 'VETETH', 'VETEUR', 'VETGBP', 'VETTRY', 'VETUSDT', 'VGXBTC', 'VGXETH', 'VGXUSDT', 'VIABNB', 'VIABTC', 'VIAETH', 'VIBBTC', 'VIBBUSD', 'VIBEBTC', 'VIBEETH', 'VIBETH', 'VIDTBTC', 'VIDTBUSD', 'VIDTUSDT', 'VITEBNB', 'VITEBTC', 'VITEUSDT', 'VOXELBNB', 'VOXELBTC', 'VOXELBUSD', 'VOXELETH', 'VOXELUSDT', 'VTHOBNB', 'VTHOBUSD', 'VTHOUSDT', 'WABIBNB', 'WABIBTC', 'WABIETH', 'WANBNB', 'WANBTC', 'WANETH', 'WANUSDT', 'WAVESBNB', 'WAVESBTC', 'WAVESBUSD', 'WAVESETH', 'WAVESEUR', 'WAVESPAX', 'WAVESRUB', 'WAVESTRY', 'WAVESTUSD', 'WAVESUSDC', 'WAVESUSDT', 'WAXPBNB', 'WAXPBTC', 'WAXPBUSD', 'WAXPUSDT', 'WBTCBTC', 'WBTCBUSD', 'WBTCETH', 'WINBNB', 'WINBRL', 'WINBTC', 'WINBUSD', 'WINEUR', 'WINGBNB', 'WINGBTC', 'WINGBUSD', 'WINGETH', 'WINGSBTC', 'WINGSETH', 'WINGUSDT', 'WINTRX', 'WINUSDC', 'WINUSDT', 'WNXMBNB', 'WNXMBTC', 'WNXMBUSD', 'WNXMUSDT', 'WOOBNB', 'WOOBTC', 'WOOBUSD', 'WOOUSDT', 'WPRBTC', 'WPRETH', 'WRXBNB', 'WRXBTC', 'WRXBUSD', 'WRXEUR', 'WRXUSDT', 'WTCBNB', 'WTCBTC', 'WTCETH', 'WTCUSDT', 'XECBUSD', 'XECUSDT', 'XEMBNB', 'XEMBTC', 'XEMBUSD', 'XEMETH', 'XEMUSDT', 'XLMBNB', 'XLMBTC', 'XLMBUSD', 'XLMDOWNUSDT', 'XLMETH', 'XLMEUR', 'XLMPAX', 'XLMTRY', 'XLMTUSD', 'XLMUPUSDT', 'XLMUSDC', 'XLMUSDT', 'XMRBNB', 'XMRBTC', 'XMRBUSD', 'XMRETH', 'XMRUSDT', 'XNOBTC', 'XNOBUSD', 'XNOETH', 'XNOUSDT', 'XRPAUD', 'XRPBEARBUSD', 'XRPBEARUSDT', 'XRPBIDR', 'XRPBKRW', 'XRPBNB', 'XRPBRL', 'XRPBTC', 'XRPBULLBUSD', 'XRPBULLUSDT', 'XRPBUSD', 'XRPDOWNUSDT', 'XRPETH', 'XRPEUR', 'XRPGBP', 'XRPNGN', 'XRPPAX', 'XRPRUB', 'XRPTRY', 'XRPTUSD', 'XRPUPUSDT', 'XRPUSDC', 'XRPUSDT', 'XTZBNB', 'XTZBTC', 'XTZBUSD', 'XTZDOWNUSDT', 'XTZETH', 'XTZTRY', 'XTZUPUSDT', 'XTZUSDT', 'XVGBTC', 'XVGBUSD', 'XVGETH', 'XVGUSDT', 'XVSBNB', 'XVSBTC', 'XVSBUSD', 'XVSUSDT', 'XZCBNB', 'XZCBTC', 'XZCETH', 'XZCUSDT', 'XZCXRP', 'YFIBNB', 'YFIBTC', 'YFIBUSD', 'YFIDOWNUSDT', 'YFIEUR', 'YFIIBNB', 'YFIIBTC', 'YFIIBUSD', 'YFIIUSDT', 'YFIUPUSDT', 'YFIUSDT', 'YGGBNB', 'YGGBTC', 'YGGBUSD', 'YGGUSDT', 'YOYOBNB', 'YOYOBTC', 'YOYOETH', 'ZECBNB', 'ZECBTC', 'ZECBUSD', 'ZECETH', 'ZECPAX', 'ZECTUSD', 'ZECUSDC', 'ZECUSDT', 'ZENBNB', 'ZENBTC', 'ZENBUSD', 'ZENETH', 'ZENUSDT', 'ZILBIDR', 'ZILBNB', 'ZILBTC', 'ZILBUSD', 'ZILETH', 'ZILEUR', 'ZILTRY', 'ZILUSDT', 'ZRXBNB', 'ZRXBTC', 'ZRXBUSD', 'ZRXETH', 'ZRXUSDT']

    return my_liste

